### PR TITLE
chore: Add .gitignore

### PR DESCRIPTION
**Pull request by mirusu400**
There are no gitignore in this repo, so some useless files (such as `__pycache__`) are included in the whole repo. So I add default .gitignore.

### CODE REVIEW

**Comment by SpreadSheets600** [comment]
@mirusu400 done in #18

**Comment by mirusu400** [comment]
@SpreadSheets600 Can you add `hacktoberfest-accepted` label even it is not merged? :D

**Comment by SpreadSheets600** [comment]
@mirusu400 oki

**Comment by mirusu400** [comment]
hi, @SpreadSheets600 thank you for adding label, but cause of the emoji this PR is not accepted in hacktoberfest. Shall you remove the emoji and remain only `hacktoberfest` and `hacktoberfest-accepted` plaintext label?

**Comment by SpreadSheets600** [comment]
@mirusu400 I am really sorry I will fix that

**Pull request closed without merging**
